Icons show what back sends now
TomasKireilis/geliu-e-parduotuve pull request #14
Opened 2021-03-30 17:57 UTC by kauke88

2021-04-12 16:22 UTC, mdovile requested changes
![image](https://user-images.githubusercontent.com/53144067/114427936-45179200-9bc4-11eb-9e87-6cd283de6ba7.png)

kažin ne po šito atsirado kažkokie infinity eur? :D

2021-04-12 16:22 UTC, mdovile commented on src/Service/FlowerService.js
> +            tempObject.type = "flowerBouquet";
Nelabai suprantu kodėl šitas keitimas daromas, negalim toje vietoje kur naudojam ir mes persivadinti į FLOWERPACK?

2021-04-12 16:22 UTC, mdovile commented on src/Service/FlowerService.js
> +import React from "react";
Nenaudojamas importas

2021-04-12 16:34 UTC, TomasKireilis commented on src/Service/FlowerService.js
> +            tempObject.type = "flowerBouquet";
Yes, mes galime ta padaryti . Bet tai jeigu tu vietu bus daugiau nei viena ir ateis kitoks stringas ( ty backe kazkas padarys breaking change), nebutu geriau td tureti toki mapperi kuris leistu UI domainui nesirupinti ateinancios informacijos teisingumu?

2021-04-12 16:37 UTC, TomasKireilis commented
Dėl infinity. Cia jau buvo iš seniau nepagalvota kas bus jei nebus duomenu. tokiu atveju jis grazina nzn (0,0)? turbut arba (null,null)? ir tas slideris nezino kaip sita apdoroti

2021-04-12 16:39 UTC, TomasKireilis commented
Jei nera duomenu padaryk jog slideris butu 0,0 arba jei sitas neiseina daryk 0,1 arba padaryk css hide element

2021-04-12 16:40 UTC, TomasKireilis commented on src/Service/FlowerService.js
> +            tempObject.type = "flowerBouquet";
ps: overall tai tikrai nera normalus mano paaiskintos problemos sprendimas

2021-04-14 15:48 UTC, mdovile approved these changes

2021-04-14 15:50 UTC, merged