Shopping cart page with a table of items
TomasKireilis/geliu-e-parduotuve pull request #2
Opened 2021-03-17 18:18 UTC by mdovile

![cart-tableą](https://user-images.githubusercontent.com/53144067/111517179-7637aa80-875d-11eb-9c9e-4b34c3a6c383.png)

/cart 

Paskui gal geriau padarysim

2021-03-17 18:38 UTC, TomasKireilis requested changes

2021-03-17 18:38 UTC, TomasKireilis commented on public/index.html
> +    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
tau sito nereikia index arba app .js yra importintas stylesheetas už tave. ir jei gerai pamenu vieno importo uztenka visam solutionui

2021-03-17 18:38 UTC, TomasKireilis commented on src/App.css
> +}
geriau butu kazkas tokio height pvz: height: 5vh; max-height: 120px,min-height: 30px (cia random tuos skaicius imeciau reikia ziureti kaip graziai atrodo)

2021-03-17 18:38 UTC, TomasKireilis commented on src/ShoppingCartRow.js
> +                    style={{ border: 'none', boxShadow: 'none', backgroundColor: 'transparent' }}
siaip gerai kaip ir cia yra bet galbut vertetu iskelti i atskira klase?

2021-03-17 18:38 UTC, TomasKireilis commented on src/ShoppingCartTable.js
> +              <th></th>
vietoj visu text allign gali naudoti css klase .tr th{}

2021-03-17 18:38 UTC, TomasKireilis commented on src/ShoppingCartTable.js
> +              <th></th>
<th></th> cia tiesiog tuscias?

2021-03-17 19:28 UTC, mdovile commented on src/ShoppingCartTable.js
> +              <th></th>
Bandysiu dar kartą, bet man netgi su !important nepavyko overridinti bootstrapo stiliaus naudojant klasę ir panašiai, tik inline kai padarau tada pradingsta (left alignmentas iš bootstrapo pareina)

2021-03-17 19:29 UTC, mdovile commented on src/ShoppingCartTable.js
> +              <th></th>
Jo :D Nžn ar reikia rašyti "paveikslėlis", ir taip matys

2021-03-18 11:21 UTC, TomasKireilis approved these changes

2021-03-18 11:32 UTC, merged