Added account login popup
TomasKireilis/geliu-e-parduotuve pull request #22
Opened 2021-05-05 08:28 UTC by TomasKireilis

2021-05-05 08:32 UTC, TomasKireilis reviewed
Dar nera call i serveri

2021-05-06 07:12 UTC, mdovile requested changes

2021-05-06 07:12 UTC, mdovile commented on src/AcountPopups/AccountLoginPopup.js
> +                    Mes niekada nebendrinsime jūsų el. Pašto
pašto iš mažosios būtų gražiau

2021-05-06 07:12 UTC, mdovile commented on src/AcountPopups/AccountLoginPopup.js
> +    console.log(loginInfo);
Ar čia debuginimui palikta netyčia?

2021-05-12 10:04 UTC, TomasKireilis commented on src/Service/FlowerService.js
> +// }
Next PR. laukia endpointo

2021-05-12 11:44 UTC, mdovile commented on src/AcountPopups/AccountLoginPopup.js
> +    console.log(loginInfo);
Kodėl šitas resolved? :D

2021-05-12 11:46 UTC, TomasKireilis commented on src/AcountPopups/AccountLoginPopup.js
> +    console.log(loginInfo);
![image](https://user-images.githubusercontent.com/57706951/117969991-c764b480-b330-11eb-8f8c-fdcdadb518e5.png)

2021-05-12 11:46 UTC, TomasKireilis commented on src/AcountPopups/AccountLoginPopup.js
> +    console.log(loginInfo);
outdated

2021-05-12 11:47 UTC, mdovile commented on src/Service/FlowerService.js
>    console.log(response);
Nžn gal nereikia console logint "productione"

2021-05-12 11:49 UTC, TomasKireilis commented on src/Service/FlowerService.js
>    console.log(response);
cia meta nepabaige yra kitas taskas sitam

2021-05-12 11:52 UTC, mdovile approved these changes

2021-05-12 11:54 UTC, merged