Gep 24
TomasKireilis/geliu-e-parduotuve pull request #30
Opened 2021-05-14 17:51 UTC by kauke88

Registration form created with call to back + checked response
B: Toast behind a popup if registration data is incorrect

2021-05-14 18:01 UTC, TomasKireilis commented
![image](https://user-images.githubusercontent.com/57706951/118310630-8b2f8080-b4f7-11eb-8e8f-4970939ae7f4.png)

2021-05-14 18:01 UTC, TomasKireilis commented
kai errorai nerodo erroro popupo

2021-05-14 18:02 UTC, TomasKireilis commented on src/AcountPopups/RegisterAccountPopup.js
> +                      setRegistrationData(registrationData);
truksta check()

2021-05-14 18:05 UTC, TomasKireilis requested changes

2021-05-14 18:05 UTC, TomasKireilis commented on src/App.css
> +  z-index: 200000 !important;
cia bent kazka daro? jei ne kam keist?

2021-05-22 05:59 UTC, mdovile requested changes
Ar dar aktyvus šitas PR? Reikia Tomo komentarus sutvarkyti

2021-05-22 09:55 UTC, mdovile requested changes

2021-05-22 09:55 UTC, mdovile commented on src/AcountPopups/RegisterAccountPopup.js
> +    console.log(response);
Console log ištrinti

2021-05-22 09:55 UTC, mdovile commented on src/Service/RegistrationService.js
> +    console.log(response.status);
Ištrinti

2021-05-22 15:39 UTC, TomasKireilis approved these changes

2021-05-22 15:43 UTC, mdovile approved these changes

2021-05-22 15:48 UTC, merged